image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

build:
  project: code/cpp/std_normal_distribution
  verbosity: minimal

matrix:
  fast_finish: false

configuration:
  - Debug
  - Release

build_script:
  - sh: pwd
  - cd code/cpp/std_normal_distribution
  - mkdir build
  - cd build
  - cmake -A%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build --config %CONFIGURATION% .

test_script:
  - sh: pwd
  - cd code/cpp/std_normal_distribution
  - mkdir build
  - cd build
  - cmake -A%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build --config %CONFIGURATION% .
  - ctest
